const vk = @import("../vk.zig");

pub const LayerProperties = extern struct {
    layerName: [vk.MAX_EXTENSION_NAME_SIZE]u8,
    specVersion: u32,
    implementationVersion: u32,
    description: [vk.MAX_DESCRIPTION_SIZE]u8,
};

pub const ExtensionProperties = extern struct {
    extensionName: [vk.MAX_EXTENSION_NAME_SIZE]u8,
    specVersion: u32,
};

pub const ApplicationInfo = extern struct {
    sType: vk.StructureType,
    pNext: ?*const anyopaque,
    pApplicationName: ?[*:0]const u8,
    applicationVersion: u32,
    pEngineName: ?[*:0]const u8,
    engineVersion: u32,
    apiVersion: u32,
};

pub const InstanceCreateInfo = extern struct {
    sType: vk.StructureType,
    pNext: ?*const anyopaque,
    flags: vk.InstanceCreateFlags,
    pApplicationInfo: ?*const ApplicationInfo,
    enabledLayerCount: u32,
    ppEnabledLayerNames: ?[*]const [*:0]const u8,
    enabledExtensionCount: u32,
    ppEnabledExtensionNames: ?[*]const [*:0]const u8,
};

pub const AllocationCallbacks = extern struct {
    pUserData: ?*anyopaque,
    pfnAllocation: vk.PFN_vkAllocationFunction,
    pfnReallocation: vk.PFN_vkReallocationFunction,
    pfnFree: vk.PFN_vkFreeFunction,
    pfnInternalAllocation: ?vk.PFN_vkInternalAllocationNotification,
    pfnInternalFree: ?vk.PFN_vkInternalFreeNotification,
};

pub const PhysicalDeviceLimits = extern struct {
    maxImageDimension1D: u32,
    maxImageDimension2D: u32,
    maxImageDimension3D: u32,
    maxImageDimensionCube: u32,
    maxImageArrayLayers: u32,
    maxTexelBufferElements: u32,
    maxUniformBufferRange: u32,
    maxStorageBufferRange: u32,
    maxPushConstantsSize: u32,
    maxMemoryAllocationCount: u32,
    maxSamplerAllocationCount: u32,
    bufferImageGranularity: vk.DeviceSize,
    sparseAddressSpaceSize: vk.DeviceSize,
    maxBoundDescriptorSets: u32,
    maxPerStageDescriptorSamplers: u32,
    maxPerStageDescriptorUniformBuffers: u32,
    maxPerStageDescriptorStorageBuffers: u32,
    maxPerStageDescriptorSampledImages: u32,
    maxPerStageDescriptorStorageImages: u32,
    maxPerStageDescriptorInputAttachments: u32,
    maxPerStageResources: u32,
    maxDescriptorSetSamplers: u32,
    maxDescriptorSetUniformBuffers: u32,
    maxDescriptorSetUniformBuffersDynamic: u32,
    maxDescriptorSetStorageBuffers: u32,
    maxDescriptorSetStorageBuffersDynamic: u32,
    maxDescriptorSetSampledImages: u32,
    maxDescriptorSetStorageImages: u32,
    maxDescriptorSetInputAttachments: u32,
    maxVertexInputAttributes: u32,
    maxVertexInputBindings: u32,
    maxVertexInputAttributeOffset: u32,
    maxVertexInputBindingStride: u32,
    maxVertexOutputComponents: u32,
    maxTessellationGenerationLevel: u32,
    maxTessellationPatchSize: u32,
    maxTessellationControlPerVertexInputComponents: u32,
    maxTessellationControlPerVertexOutputComponents: u32,
    maxTessellationControlPerPatchOutputComponents: u32,
    maxTessellationControlTotalOutputComponents: u32,
    maxTessellationEvaluationInputComponents: u32,
    maxTessellationEvaluationOutputComponents: u32,
    maxGeometryShaderInvocations: u32,
    maxGeometryInputComponents: u32,
    maxGeometryOutputComponents: u32,
    maxGeometryOutputVertices: u32,
    maxGeometryTotalOutputComponents: u32,
    maxFragmentInputComponents: u32,
    maxFragmentOutputAttachments: u32,
    maxFragmentDualSrcAttachments: u32,
    maxFragmentCombinedOutputResources: u32,
    maxComputeSharedMemorySize: u32,
    maxComputeWorkGroupCount: [3]u32,
    maxComputeWorkGroupInvocations: u32,
    maxComputeWorkGroupSize: [3]u32,
    subPixelPrecisionBits: u32,
    subTexelPrecisionBits: u32,
    mipmapPrecisionBits: u32,
    maxDrawIndexedIndexValue: u32,
    maxDrawIndirectCount: u32,
    maxSamplerLodBias: f32,
    maxSamplerAnisotropy: f32,
    maxViewports: u32,
    maxViewportDimensions: [2]u32,
    viewportBoundsRange: [2]f32,
    viewportSubPixelBits: u32,
    minMemoryMapAlignment: isize,
    minTexelBufferOffsetAlignment: vk.DeviceSize,
    minUniformBufferOffsetAlignment: vk.DeviceSize,
    minStorageBufferOffsetAlignment: vk.DeviceSize,
    minTexelOffset: i32,
    maxTexelOffset: u32,
    minTexelGatherOffset: i32,
    maxTexelGatherOffset: u32,
    minInterpolationOffset: f32,
    maxInterpolationOffset: f32,
    subPixelInterpolationOffsetBits: u32,
    maxFramebufferWidth: u32,
    maxFramebufferHeight: u32,
    maxFramebufferLayers: u32,
    framebufferColorSampleCounts: vk.SampleCountFlags,
    framebufferDepthSampleCounts: vk.SampleCountFlags,
    framebufferStencilSampleCounts: vk.SampleCountFlags,
    framebufferNoAttachmentsSampleCounts: vk.SampleCountFlags,
    maxColorAttachments: u32,
    sampledImageColorSampleCounts: vk.SampleCountFlags,
    sampledImageIntegerSampleCounts: vk.SampleCountFlags,
    sampledImageDepthSampleCounts: vk.SampleCountFlags,
    sampledImageStencilSampleCounts: vk.SampleCountFlags,
    storageImageSampleCounts: vk.SampleCountFlags,
    maxSampleMaskWords: u32,
    timestampComputeAndGraphics: vk.Bool32,
    timestampPeriod: f32,
    maxClipDistances: u32,
    maxCullDistances: u32,
    maxCombinedClipAndCullDistances: u32,
    discreteQueuePriorities: u32,
    pointSizeRange: [2]f32,
    lineWidthRange: [2]f32,
    pointSizeGranularity: f32,
    lineWidthGranularity: f32,
    strictLines: vk.Bool32,
    standardSampleLocations: vk.Bool32,
    optimalBufferCopyOffsetAlignment: vk.DeviceSize,
    optimalBufferCopyRowPitchAlignment: vk.DeviceSize,
    nonCoherentAtomSize: vk.DeviceSize,
};

pub const PhysicalDeviceSparseProperties = extern struct {
    residencyStandard2DBlockShape: vk.Bool32,
    residencyStandard2DMultisampleBlockShape: vk.Bool32,
    residencyStandard3DBlockShape: vk.Bool32,
    residencyAlignedMipSize: vk.Bool32,
    residencyNonResidentStrict: vk.Bool32,
};

pub const PhysicalDeviceProperties = extern struct {
    apiVersion: u32,
    driverVersion: u32,
    vendorID: u32,
    deviceID: u32,
    deviceType: vk.PhysicalDeviceType,
    deviceName: [vk.MAX_PHYSICAL_DEVICE_NAME_SIZE]u8,
    pipelineCacheUUID: [vk.UUID_SIZE]u8,
    limits: PhysicalDeviceLimits,
    sparseProperties: PhysicalDeviceSparseProperties,
};
